[features]
seeds = false
skip-lint = false

[programs.devnet]
x100_nft = "FDPnHfvDDmsDQ4uy2qVzwjjZGeKaAVRT38wGFNPykhJC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/x100_nft"]
types = "target/types" 